# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vector/code/c++/yuvviewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vector/code/c++/yuvviewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/vector/code/c++/yuvviewer && $(CMAKE_COMMAND) -E cmake_progress_start /home/vector/code/c++/yuvviewer/CMakeFiles /home/vector/code/c++/yuvviewer/src/pandora_client/CMakeFiles/progress.marks
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f CMakeFiles/Makefile2 src/pandora_client/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vector/code/c++/yuvviewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f CMakeFiles/Makefile2 src/pandora_client/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f CMakeFiles/Makefile2 src/pandora_client/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f CMakeFiles/Makefile2 src/pandora_client/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/vector/code/c++/yuvviewer && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/pandora_client/CMakeFiles/pandora_client.dir/rule:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f CMakeFiles/Makefile2 src/pandora_client/CMakeFiles/pandora_client.dir/rule
.PHONY : src/pandora_client/CMakeFiles/pandora_client.dir/rule

# Convenience name for target.
pandora_client: src/pandora_client/CMakeFiles/pandora_client.dir/rule

.PHONY : pandora_client

# fast build rule for target.
pandora_client/fast:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f src/pandora_client/CMakeFiles/pandora_client.dir/build.make src/pandora_client/CMakeFiles/pandora_client.dir/build
.PHONY : pandora_client/fast

src/pandora_client.o: src/pandora_client.c.o

.PHONY : src/pandora_client.o

# target to build an object file
src/pandora_client.c.o:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f src/pandora_client/CMakeFiles/pandora_client.dir/build.make src/pandora_client/CMakeFiles/pandora_client.dir/src/pandora_client.c.o
.PHONY : src/pandora_client.c.o

src/pandora_client.i: src/pandora_client.c.i

.PHONY : src/pandora_client.i

# target to preprocess a source file
src/pandora_client.c.i:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f src/pandora_client/CMakeFiles/pandora_client.dir/build.make src/pandora_client/CMakeFiles/pandora_client.dir/src/pandora_client.c.i
.PHONY : src/pandora_client.c.i

src/pandora_client.s: src/pandora_client.c.s

.PHONY : src/pandora_client.s

# target to generate assembly for a file
src/pandora_client.c.s:
	cd /home/vector/code/c++/yuvviewer && $(MAKE) -f src/pandora_client/CMakeFiles/pandora_client.dir/build.make src/pandora_client/CMakeFiles/pandora_client.dir/src/pandora_client.c.s
.PHONY : src/pandora_client.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pandora_client"
	@echo "... src/pandora_client.o"
	@echo "... src/pandora_client.i"
	@echo "... src/pandora_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/vector/code/c++/yuvviewer && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

